const SERVICE_PROVIDERS = [
  {
    id: "transformers",
    displayName: "Browser (Transformers.js)",
    requiresApiKey: false,
    supportsOptionalApiKey: true,
    noKeyDemo: true,
    defaultModel: "qwen2.5-0.5b",
    apiBase: "browser://transformers",
    placeholder: "no key — runs in this tab",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 2048,
    preferredModels: ["qwen2.5-0.5b", "smollm2-360m", "qwen2.5-1.5b"],
    chatModelTypes: ["chat", "code"],
  },
  {
    id: "duckai",
    displayName: "Duck.ai (free)",
    requiresApiKey: false,
    supportsOptionalApiKey: true,
    noKeyDemo: true,
    defaultModel: "gpt-5.4-mini",
    apiBase: "https://duckduckgo.com/duckchat/v1",
    apiKeyUrl: "https://duck.ai",
    placeholder: "no key — DuckDuckGo Duck.ai",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 32000,
    chatModelTypes: ["chat", "code"],
    preferredModels: ["gpt-5.4-mini", "gpt-5.6-luna", "claude-haiku-4-5", "mistral-small-2603", "tinfoil/gpt-oss-120b", "tinfoil/gemma4-31b"],
  },
  {
    id: "freeai",
    displayName: "Free.ai",
    requiresApiKey: false,
    supportsOptionalApiKey: true,
    defaultModel: "qwen7b",
    apiBase: "https://api.free.ai/v1",
    apiKeyUrl: "https://free.ai/",
    placeholder: "optional — demo uses qwen7b",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 32768,
    noKeyDemo: true,
    chatModelTypes: ["chat", "code"],
    preferredModels: ["qwen7b", "qwen-coder"],
  },
  {
    id: "nvidia",
    displayName: "NVIDIA NIM",
    requiresApiKey: true,
    defaultModel: "stepfun-ai/step-3.7-flash",
    apiBase: "https://integrate.api.nvidia.com/v1",
    apiKeyUrl: "https://build.nvidia.com/settings/api-keys",
    placeholder: "nvapi-...",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 32768,
  },
  {
    id: "openai",
    displayName: "OpenAI",
    requiresApiKey: true,
    defaultModel: "gpt-4o-mini",
    apiBase: "https://api.openai.com/v1",
    apiKeyUrl: "https://platform.openai.com/api-keys",
    placeholder: "sk-...",
    supportsTools: true,
    supportsStreaming: true,
    supportsPdf: true,
    contextWindowTokens: 128000,
  },
  {
    id: "deepseek",
    displayName: "DeepSeek",
    requiresApiKey: true,
    defaultModel: "deepseek-chat",
    apiBase: "https://api.deepseek.com",
    apiKeyUrl: "https://platform.deepseek.com/api_keys",
    placeholder: "sk-...",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 65536,
  },
  {
    id: "groq",
    displayName: "Groq",
    requiresApiKey: true,
    defaultModel: "llama-3.1-8b-instant",
    apiBase: "https://api.groq.com/openai/v1",
    apiKeyUrl: "https://console.groq.com/keys",
    placeholder: "gsk_...",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 32768,
  },
  {
    id: "mistral",
    displayName: "Mistral",
    requiresApiKey: true,
    defaultModel: "mistral-small-latest",
    apiBase: "https://api.mistral.ai/v1",
    apiKeyUrl: "https://console.mistral.ai/api-keys",
    placeholder: "...",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 32768,
  },
  {
    id: "openrouter",
    displayName: "OpenRouter",
    requiresApiKey: true,
    defaultModel: "cohere/north-mini-code:free",
    apiBase: "https://openrouter.ai/api/v1",
    apiKeyUrl: "https://openrouter.ai/settings/keys",
    placeholder: "sk-or-v1-...",
    supportsTools: true,
    supportsStreaming: true,
    supportsPdf: true,
    contextWindowTokens: 128000,
    freeToolModels: [
      { id: "openrouter/free", label: "Free Models Router (auto)" },
      { id: "cohere/north-mini-code:free", label: "Cohere North Mini Code (free)" },
      { id: "openai/gpt-oss-20b:free", label: "OpenAI gpt-oss-20b (free)" },
      { id: "nvidia/nemotron-3-nano-30b-a3b:free", label: "Nemotron 3 Nano 30B (free)" },
      { id: "nvidia/nemotron-3-super:free", label: "Nemotron 3 Super (free)" },
      { id: "poolside/laguna-xs-2.1:free", label: "Poolside Laguna XS (free)" },
      { id: "poolside/laguna-s-2.1:free", label: "Poolside Laguna S (free)" },
      { id: "google/gemma-4-26b-a4b:free", label: "Gemma 4 26B A4B (free)" },
      { id: "google/gemma-4-31b:free", label: "Gemma 4 31B (free)" },
    ],
  },
  {
    id: "xai",
    displayName: "xAI (Grok)",
    requiresApiKey: true,
    defaultModel: "grok-2-latest",
    apiBase: "https://api.x.ai/v1",
    apiKeyUrl: "https://console.x.ai",
    placeholder: "xai-...",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 131072,
  },
  {
    id: "gemini",
    displayName: "Google Gemini",
    requiresApiKey: true,
    defaultModel: "gemini-2.0-flash",
    apiBase: "https://generativelanguage.googleapis.com/v1beta/openai",
    apiKeyUrl: "https://aistudio.google.com/apikey",
    placeholder: "AIza...",
    supportsTools: true,
    supportsStreaming: true,
    supportsPdf: true,
    contextWindowTokens: 1000000,
  },
  {
    id: "together",
    displayName: "Together AI",
    requiresApiKey: true,
    defaultModel: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
    apiBase: "https://api.together.xyz/v1",
    apiKeyUrl: "https://api.together.ai/settings/api-keys",
    placeholder: "...",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 32768,
  },
  {
    id: "cerebras",
    displayName: "Cerebras",
    requiresApiKey: true,
    defaultModel: "llama3.1-8b",
    apiBase: "https://api.cerebras.ai/v1",
    apiKeyUrl: "https://cloud.cerebras.ai/",
    placeholder: "csk-...",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 32768,
  },
  {
    id: "huggingface",
    displayName: "Hugging Face",
    requiresApiKey: true,
    defaultModel: "meta-llama/Meta-Llama-3.1-8B-Instruct",
    apiBase: "https://router.huggingface.co/v1",
    apiKeyUrl: "https://huggingface.co/settings/tokens",
    placeholder: "hf_...",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 32768,
  },
  {
    id: "deepinfra",
    displayName: "DeepInfra",
    requiresApiKey: true,
    defaultModel: "meta-llama/Meta-Llama-3.1-8B-Instruct",
    apiBase: "https://api.deepinfra.com/v1/openai",
    apiKeyUrl: "https://deepinfra.com/dash/api_keys",
    placeholder: "...",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 32768,
  },
  {
    id: "fireworks",
    displayName: "Fireworks AI",
    requiresApiKey: true,
    defaultModel: "accounts/fireworks/models/llama-v3p1-8b-instruct",
    apiBase: "https://api.fireworks.ai/inference/v1",
    apiKeyUrl: "https://app.fireworks.ai/settings/users/api-keys",
    placeholder: "fw_...",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 32768,
  },
  {
    id: "venice",
    displayName: "Venice Agent",
    requiresApiKey: true,
    defaultModel: "venice-uncensored",
    apiBase: "https://api.venice.ai/api/v1",
    apiKeyUrl: "https://venice.ai/settings/api/keys",
    placeholder: "venice key — free tier, no card",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 128000,
    preferredModels: ["venice-uncensored", "llama-3.3-70b", "qwen3-235b", "zai-org-glm-5"],
  },
  {
    id: "ollama",
    displayName: "Ollama (local)",
    requiresApiKey: false,
    supportsOptionalApiKey: true,
    defaultModel: "llama3.2",
    apiBase: "http://127.0.0.1:11434/v1",
    placeholder: "(optional)",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 32768,
  },
  {
    id: "openai-compatible",
    displayName: "Custom OpenAI-compatible",
    requiresApiKey: false,
    supportsOptionalApiKey: true,
    defaultModel: "",
    apiBase: "",
    placeholder: "optional key",
    supportsTools: true,
    supportsStreaming: true,
    contextWindowTokens: 32768,
    isCustom: true,
  },
];

/** @deprecated map view for older slash cmds */
const PROVIDERS = Object.fromEntries(
  SERVICE_PROVIDERS.map((p) => [
    p.id,
    {
      id: p.id,
      label: p.displayName,
      apiBase: p.apiBase || "",
      apiModel: p.defaultModel || "",
      placeholder: p.placeholder || "...",
    },
  ]),
);

